### ISSUE TITLE
Creating custom coefficient tables

### ISSUE THREAD

**Issue by ltloc115** [bobh/ESP32Talkie#1]
Hi, I was trying to create the speech I need since the existing voices miss some of the words. And since you were able to put a whole song in your own example, can you explain how you did that? I have tried Audacity and created an unsigned 8 bit, 8kHz WAV file, which I then used HxD to get the coefficient table. However, it's pretty large and the sound isn't right.

**Comment by bobh** [comment]
Hi,
For talkie, I just ported the C code in the library to work on the ESP32 instead of Arduino. So my effort was mainly just rewriting the interrupts. That speech example was from the original library—I included it just to show compatibility.
There was an app for the Mac someone wrote that created the LPC coefficients from a wave file and I played around with that but can’t remember what the app was named or how successful it was.
bobh

**Comment by ltloc115** [comment]
Ah, that's how it is. Well, thanks anyways. I'll try other ways I can think of then.
